<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('p_permissions')->delete();

        \DB::table('p_permissions')->insert([
            ['name' => "admin.dashboard", 'guard_name' => 'web'],
            ['name' => "admin.user", 'guard_name' => 'web'],
            ['name' => "admin.user.excel", 'guard_name' => 'web'],
            ['name' => "admin.user.store", 'guard_name' => 'web'],
            ['name' => "admin.user.delete", 'guard_name' => 'web'],
            ['name' => "admin.user.find", 'guard_name' => 'web'],
            ['name' => "admin.user.update", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data.add", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data.edit", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data.delete", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data.insert", 'guard_name' => 'web'],
            ['name' => "admin.artikel.data.update", 'guard_name' => 'web'],
            ['name' => "admin.artikel.kategori", 'guard_name' => 'web'],
            ['name' => "admin.artikel.kategori.select2", 'guard_name' => 'web'],
            ['name' => "admin.artikel.kategori.insert", 'guard_name' => 'web'],
            ['name' => "admin.artikel.kategori.delete", 'guard_name' => 'web'],
            ['name' => "admin.artikel.kategori.update", 'guard_name' => 'web'],
            ['name' => "admin.artikel.tag", 'guard_name' => 'web'],
            ['name' => "admin.artikel.tag.select2", 'guard_name' => 'web'],
            ['name' => "admin.artikel.tag.insert", 'guard_name' => 'web'],
            ['name' => "admin.artikel.tag.delete", 'guard_name' => 'web'],
            ['name' => "admin.artikel.tag.update", 'guard_name' => 'web'],
            ['name' => "admin.galeri", 'guard_name' => 'web'],
            ['name' => "admin.galeri.select2", 'guard_name' => 'web'],
            ['name' => "admin.galeri.insert", 'guard_name' => 'web'],
            ['name' => "admin.galeri.delete", 'guard_name' => 'web'],
            ['name' => "admin.galeri.update", 'guard_name' => 'web'],
            ['name' => "admin.social_media", 'guard_name' => 'web'],
            ['name' => "admin.social_media.insert", 'guard_name' => 'web'],
            ['name' => "admin.social_media.delete", 'guard_name' => 'web'],
            ['name' => "admin.social_media.update", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform.member", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform.find", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform.insert", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform.update", 'guard_name' => 'web'],
            ['name' => "admin.pendaftaran.gform.delete", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_depan_atas", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_depan_atas.find", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_depan_atas.insert", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_depan_atas.update", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_depan_atas.delete", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_admin_atas", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_admin_atas.find", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_admin_atas.insert", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_admin_atas.update", 'guard_name' => 'web'],
            ['name' => "admin.utility.notif_admin_atas.delete", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional.find", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional.insert", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional.update", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional.delete", 'guard_name' => 'web'],
            ['name' => "admin.utility.hari_besar_nasional.list_error", 'guard_name' => 'web'],
            ['name' => "admin.user_access.permission", 'guard_name' => 'web'],
            ['name' => "admin.user_access.permission.store", 'guard_name' => 'web'],
            ['name' => "admin.user_access.permission.delete", 'guard_name' => 'web'],
            ['name' => "admin.user_access.permission.update", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role.create", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role.edit", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role.store", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role.update", 'guard_name' => 'web'],
            ['name' => "admin.user_access.role.delete", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.save", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.insert", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.update", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.delete", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.list", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.find", 'guard_name' => 'web'],
            ['name' => "admin.menu.admin.parent_list", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.save", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.insert", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.update", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.delete", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.list", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.find", 'guard_name' => 'web'],
            ['name' => "admin.menu.frontend.parent_list", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.save.app", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.save.meta", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.meta", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.meta.insert", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.meta.update", 'guard_name' => 'web'],
            ['name' => "admin.setting.admin.meta.delete", 'guard_name' => 'web'],
            ['name' => "admin.setting.front", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.save.app", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.save.meta", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.meta", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.meta.insert", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.meta.update", 'guard_name' => 'web'],
            ['name' => "admin.setting.front.meta.delete", 'guard_name' => 'web'],
            ['name' => "admin.setting.home", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.hero", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.poesaka", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.visi_misi", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.struktur_anggota", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.kata_alumni", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.galeri_kegiatan", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.artikel", 'guard_name' => 'web'],
            ['name' => "admin.setting.home.sensus", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq.find", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq.insert", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq.update", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq.delete", 'guard_name' => 'web'],
            ['name' => "admin.kontak.faq.setting", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list.find", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list.insert", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list.update", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list.delete", 'guard_name' => 'web'],
            ['name' => "admin.kontak.list.setting", 'guard_name' => 'web'],
            ['name' => "admin.kontak.message", 'guard_name' => 'web'],
            ['name' => "admin.kontak.message.setting", 'guard_name' => 'web'],
            ['name' => "member.dashboard", 'guard_name' => 'web'],
            ['name' => "member.password", 'guard_name' => 'web'],
            ['name' => "member.password.save", 'guard_name' => 'web'],
            ['name' => "penduduk", 'guard_name' => 'web'],
        ]);
    }
}
